/**
 * Curated destinations with verified coordinates.
 *
 * GENERATED by scripts/build-cities.mjs — do not edit by hand.
 *
 * This exists because Nominatim matches full text rather than prefixes: typing
 * "Barce" never surfaces Barcelona, and Hebrew fragments match Israeli places
 * instead of the intended city. Searching this list locally is instant, correct
 * in Hebrew, and costs no request; Nominatim remains the fallback for anywhere
 * not listed here.
 */

export const CITIES = [
  {
    "he": "פריז",
    "en": "Paris",
    "country": "צרפת",
    "countryEn": "France",
    "emoji": "🗼",
    "lat": 48.8589,
    "lng": 2.32
  },
  {
    "he": "רומא",
    "en": "Rome",
    "country": "איטליה",
    "countryEn": "Italy",
    "emoji": "🏛️",
    "lat": 41.8933,
    "lng": 12.4829
  },
  {
    "he": "פראג",
    "en": "Prague",
    "country": "צ׳כיה",
    "countryEn": "Czechia",
    "emoji": "🏰",
    "lat": 50.0875,
    "lng": 14.4213
  },
  {
    "he": "ברצלונה",
    "en": "Barcelona",
    "country": "ספרד",
    "countryEn": "Spain",
    "emoji": "🎨",
    "lat": 41.3826,
    "lng": 2.1771
  },
  {
    "he": "מדריד",
    "en": "Madrid",
    "country": "ספרד",
    "countryEn": "Spain",
    "emoji": "🇪🇸",
    "lat": 40.4168,
    "lng": -3.7035
  },
  {
    "he": "סביליה",
    "en": "Seville",
    "country": "ספרד",
    "countryEn": "Spain",
    "emoji": "💃",
    "lat": 37.3886,
    "lng": -5.9953
  },
  {
    "he": "ולנסיה",
    "en": "Valencia",
    "country": "ספרד",
    "countryEn": "Spain",
    "emoji": "🍊",
    "lat": 39.4697,
    "lng": -0.3763
  },
  {
    "he": "מלגה",
    "en": "Malaga",
    "country": "ספרד",
    "countryEn": "Spain",
    "emoji": "🏖️",
    "lat": 36.7648,
    "lng": -4.4422
  },
  {
    "he": "איביזה",
    "en": "Ibiza",
    "country": "ספרד",
    "countryEn": "Spain",
    "emoji": "🎉",
    "lat": 38.9744,
    "lng": 1.4197
  },
  {
    "he": "לונדון",
    "en": "London",
    "country": "אנגליה",
    "countryEn": "United Kingdom",
    "emoji": "☂️",
    "lat": 51.5074,
    "lng": -0.1278
  },
  {
    "he": "אדינבורו",
    "en": "Edinburgh",
    "country": "סקוטלנד",
    "countryEn": "Scotland",
    "emoji": "🏰",
    "lat": 55.9533,
    "lng": -3.1884
  },
  {
    "he": "אמסטרדם",
    "en": "Amsterdam",
    "country": "הולנד",
    "countryEn": "Netherlands",
    "emoji": "🚲",
    "lat": 52.3731,
    "lng": 4.8925
  },
  {
    "he": "ברלין",
    "en": "Berlin",
    "country": "גרמניה",
    "countryEn": "Germany",
    "emoji": "🐻",
    "lat": 52.5174,
    "lng": 13.3951
  },
  {
    "he": "מינכן",
    "en": "Munich",
    "country": "גרמניה",
    "countryEn": "Germany",
    "emoji": "🍺",
    "lat": 48.1371,
    "lng": 11.5754
  },
  {
    "he": "פרנקפורט",
    "en": "Frankfurt",
    "country": "גרמניה",
    "countryEn": "Germany",
    "emoji": "🏦",
    "lat": 50.1106,
    "lng": 8.6821
  },
  {
    "he": "המבורג",
    "en": "Hamburg",
    "country": "גרמניה",
    "countryEn": "Germany",
    "emoji": "⚓",
    "lat": 53.5502,
    "lng": 10.0013
  },
  {
    "he": "קלן",
    "en": "Cologne",
    "country": "גרמניה",
    "countryEn": "Germany",
    "emoji": "⛪",
    "lat": 50.9384,
    "lng": 6.96
  },
  {
    "he": "וינה",
    "en": "Vienna",
    "country": "אוסטריה",
    "countryEn": "Austria",
    "emoji": "🎻",
    "lat": 48.2084,
    "lng": 16.3725
  },
  {
    "he": "זלצבורג",
    "en": "Salzburg",
    "country": "אוסטריה",
    "countryEn": "Austria",
    "emoji": "🎼",
    "lat": 47.7981,
    "lng": 13.0465
  },
  {
    "he": "טירול",
    "en": "Tyrol",
    "country": "אוסטריה",
    "countryEn": "Austria",
    "emoji": "⛰️",
    "lat": 47.2232,
    "lng": 11.5261
  },
  {
    "he": "בודפשט",
    "en": "Budapest",
    "country": "הונגריה",
    "countryEn": "Hungary",
    "emoji": "♨️",
    "lat": 47.4979,
    "lng": 19.0402
  },
  {
    "he": "אתונה",
    "en": "Athens",
    "country": "יוון",
    "countryEn": "Greece",
    "emoji": "🏺",
    "lat": 37.9756,
    "lng": 23.7348
  },
  {
    "he": "סלוניקי",
    "en": "Thessaloniki",
    "country": "יוון",
    "countryEn": "Greece",
    "emoji": "🌊",
    "lat": 40.6403,
    "lng": 22.9353
  },
  {
    "he": "רודוס",
    "en": "Rhodes",
    "country": "יוון",
    "countryEn": "Greece",
    "emoji": "🏖️",
    "lat": 36.1725,
    "lng": 27.9194
  },
  {
    "he": "כרתים",
    "en": "Heraklion",
    "country": "יוון",
    "countryEn": "Greece",
    "emoji": "🏝️",
    "lat": 35.3391,
    "lng": 25.1333
  },
  {
    "he": "סנטוריני",
    "en": "Santorini",
    "country": "יוון",
    "countryEn": "Greece",
    "emoji": "🌋",
    "lat": 36.4071,
    "lng": 25.4567
  },
  {
    "he": "מיקונוס",
    "en": "Mykonos",
    "country": "יוון",
    "countryEn": "Greece",
    "emoji": "🐚",
    "lat": 37.4514,
    "lng": 25.3923
  },
  {
    "he": "לרנקה",
    "en": "Larnaca",
    "country": "קפריסין",
    "countryEn": "Cyprus",
    "emoji": "🌅",
    "lat": 34.9236,
    "lng": 33.6236
  },
  {
    "he": "פאפוס",
    "en": "Paphos",
    "country": "קפריסין",
    "countryEn": "Cyprus",
    "emoji": "🏛️",
    "lat": 34.7744,
    "lng": 32.4232
  },
  {
    "he": "איה נאפה",
    "en": "Ayia Napa",
    "country": "קפריסין",
    "countryEn": "Cyprus",
    "emoji": "🏖️",
    "lat": 34.9893,
    "lng": 33.9962
  },
  {
    "he": "מילאנו",
    "en": "Milan",
    "country": "איטליה",
    "countryEn": "Italy",
    "emoji": "👗",
    "lat": 45.4642,
    "lng": 9.1896
  },
  {
    "he": "ונציה",
    "en": "Venice",
    "country": "איטליה",
    "countryEn": "Italy",
    "emoji": "🚤",
    "lat": 45.4372,
    "lng": 12.3346
  },
  {
    "he": "פירנצה",
    "en": "Florence",
    "country": "איטליה",
    "countryEn": "Italy",
    "emoji": "🖼️",
    "lat": 43.7698,
    "lng": 11.2556
  },
  {
    "he": "בולוניה",
    "en": "Bologna",
    "country": "איטליה",
    "countryEn": "Italy",
    "emoji": "🍝",
    "lat": 44.4938,
    "lng": 11.3426
  },
  {
    "he": "פלרמו",
    "en": "Palermo",
    "country": "איטליה",
    "countryEn": "Italy",
    "emoji": "🍋",
    "lat": 38.1112,
    "lng": 13.3524
  },
  {
    "he": "טוסקנה",
    "en": "Tuscany",
    "country": "איטליה",
    "countryEn": "Italy",
    "emoji": "🍷",
    "lat": 43.4587,
    "lng": 11.1389
  },
  {
    "he": "דולומיטים",
    "en": "Dolomites",
    "country": "איטליה",
    "countryEn": "Italy",
    "emoji": "🏔️",
    "lat": 46.2946,
    "lng": 12.0513
  },
  {
    "he": "נאפולי",
    "en": "Naples",
    "country": "איטליה",
    "countryEn": "Italy",
    "emoji": "🍕",
    "lat": 40.8359,
    "lng": 14.2488
  },
  {
    "he": "ליסבון",
    "en": "Lisbon",
    "country": "פורטוגל",
    "countryEn": "Portugal",
    "emoji": "🚋",
    "lat": 38.7078,
    "lng": -9.1366
  },
  {
    "he": "פורטו",
    "en": "Porto",
    "country": "פורטוגל",
    "countryEn": "Portugal",
    "emoji": "🍷",
    "lat": 41.1502,
    "lng": -8.6103
  },
  {
    "he": "דבלין",
    "en": "Dublin",
    "country": "אירלנד",
    "countryEn": "Ireland",
    "emoji": "☘️",
    "lat": 53.3494,
    "lng": -6.2606
  },
  {
    "he": "קופנהגן",
    "en": "Copenhagen",
    "country": "דנמרק",
    "countryEn": "Denmark",
    "emoji": "🧜",
    "lat": 55.6867,
    "lng": 12.5701
  },
  {
    "he": "שטוקהולם",
    "en": "Stockholm",
    "country": "שוודיה",
    "countryEn": "Sweden",
    "emoji": "🛥️",
    "lat": 59.3251,
    "lng": 18.0711
  },
  {
    "he": "אוסלו",
    "en": "Oslo",
    "country": "נורווגיה",
    "countryEn": "Norway",
    "emoji": "🏔️",
    "lat": 59.9133,
    "lng": 10.739
  },
  {
    "he": "הלסינקי",
    "en": "Helsinki",
    "country": "פינלנד",
    "countryEn": "Finland",
    "emoji": "❄️",
    "lat": 60.1666,
    "lng": 24.9435
  },
  {
    "he": "רייקיאוויק",
    "en": "Reykjavik",
    "country": "איסלנד",
    "countryEn": "Iceland",
    "emoji": "🌋",
    "lat": 64.146,
    "lng": -21.9422
  },
  {
    "he": "ציריך",
    "en": "Zurich",
    "country": "שווייץ",
    "countryEn": "Switzerland",
    "emoji": "🏔️",
    "lat": 47.3744,
    "lng": 8.541
  },
  {
    "he": "ז׳נבה",
    "en": "Geneva",
    "country": "שווייץ",
    "countryEn": "Switzerland",
    "emoji": "⛲",
    "lat": 46.2018,
    "lng": 6.1466
  },
  {
    "he": "לוצרן",
    "en": "Lucerne",
    "country": "שווייץ",
    "countryEn": "Switzerland",
    "emoji": "🚠",
    "lat": 47.0521,
    "lng": 8.3058
  },
  {
    "he": "אינטרלאקן",
    "en": "Interlaken",
    "country": "שווייץ",
    "countryEn": "Switzerland",
    "emoji": "⛷️",
    "lat": 46.6855,
    "lng": 7.8585
  },
  {
    "he": "שטרסבורג",
    "en": "Strasbourg",
    "country": "צרפת",
    "countryEn": "France",
    "emoji": "🥨",
    "lat": 48.5846,
    "lng": 7.7507
  },
  {
    "he": "ניס",
    "en": "Nice",
    "country": "צרפת",
    "countryEn": "France",
    "emoji": "🌴",
    "lat": 43.7009,
    "lng": 7.2684
  },
  {
    "he": "ליון",
    "en": "Lyon",
    "country": "צרפת",
    "countryEn": "France",
    "emoji": "🍷",
    "lat": 45.7578,
    "lng": 4.832
  },
  {
    "he": "מרסיי",
    "en": "Marseille",
    "country": "צרפת",
    "countryEn": "France",
    "emoji": "⛵",
    "lat": 43.2964,
    "lng": 5.3778
  },
  {
    "he": "בריסל",
    "en": "Brussels",
    "country": "בלגיה",
    "countryEn": "Belgium",
    "emoji": "🧇",
    "lat": 50.8467,
    "lng": 4.3525
  },
  {
    "he": "ורשה",
    "en": "Warsaw",
    "country": "פולין",
    "countryEn": "Poland",
    "emoji": "🏛️",
    "lat": 52.232,
    "lng": 21.0067
  },
  {
    "he": "קרקוב",
    "en": "Krakow",
    "country": "פולין",
    "countryEn": "Poland",
    "emoji": "🐉",
    "lat": 50.0469,
    "lng": 19.9972
  },
  {
    "he": "בוקרשט",
    "en": "Bucharest",
    "country": "רומניה",
    "countryEn": "Romania",
    "emoji": "🏰",
    "lat": 44.4361,
    "lng": 26.1027
  },
  {
    "he": "סופיה",
    "en": "Sofia",
    "country": "בולגריה",
    "countryEn": "Bulgaria",
    "emoji": "⛪",
    "lat": 42.6977,
    "lng": 23.3217
  },
  {
    "he": "בלגרד",
    "en": "Belgrade",
    "country": "סרביה",
    "countryEn": "Serbia",
    "emoji": "🌉",
    "lat": 44.8153,
    "lng": 20.4457
  },
  {
    "he": "זאגרב",
    "en": "Zagreb",
    "country": "קרואטיה",
    "countryEn": "Croatia",
    "emoji": "🇭🇷",
    "lat": 45.8131,
    "lng": 15.9773
  },
  {
    "he": "דוברובניק",
    "en": "Dubrovnik",
    "country": "קרואטיה",
    "countryEn": "Croatia",
    "emoji": "🏰",
    "lat": 42.6491,
    "lng": 18.094
  },
  {
    "he": "ספליט",
    "en": "Split",
    "country": "קרואטיה",
    "countryEn": "Croatia",
    "emoji": "⛵",
    "lat": 43.5116,
    "lng": 16.44
  },
  {
    "he": "לובליאנה",
    "en": "Ljubljana",
    "country": "סלובניה",
    "countryEn": "Slovenia",
    "emoji": "🐉",
    "lat": 46.05,
    "lng": 14.5069
  },
  {
    "he": "טביליסי",
    "en": "Tbilisi",
    "country": "גאורגיה",
    "countryEn": "Georgia",
    "emoji": "🍇",
    "lat": 41.6935,
    "lng": 44.8014
  },
  {
    "he": "באטומי",
    "en": "Batumi",
    "country": "גאורגיה",
    "countryEn": "Georgia",
    "emoji": "🌊",
    "lat": 41.651,
    "lng": 41.636
  },
  {
    "he": "ירוואן",
    "en": "Yerevan",
    "country": "ארמניה",
    "countryEn": "Armenia",
    "emoji": "⛰️",
    "lat": 40.1777,
    "lng": 44.5126
  },
  {
    "he": "באקו",
    "en": "Baku",
    "country": "אזרבייג׳ן",
    "countryEn": "Azerbaijan",
    "emoji": "🔥",
    "lat": 40.3756,
    "lng": 49.8328
  },
  {
    "he": "איסטנבול",
    "en": "Istanbul",
    "country": "טורקיה",
    "countryEn": "Turkey",
    "emoji": "🕌",
    "lat": 41.0064,
    "lng": 28.9759
  },
  {
    "he": "דובאי",
    "en": "Dubai",
    "country": "איחוד האמירויות",
    "countryEn": "United Arab Emirates",
    "emoji": "🌇",
    "lat": 25.0743,
    "lng": 55.1886
  },
  {
    "he": "אבו דאבי",
    "en": "Abu Dhabi",
    "country": "איחוד האמירויות",
    "countryEn": "United Arab Emirates",
    "emoji": "🕌",
    "lat": 24.4538,
    "lng": 54.3774
  },
  {
    "he": "דוחא",
    "en": "Doha",
    "country": "קטאר",
    "countryEn": "Qatar",
    "emoji": "🏙️",
    "lat": 25.3109,
    "lng": 51.5082
  },
  {
    "he": "עמאן",
    "en": "Amman",
    "country": "ירדן",
    "countryEn": "Jordan",
    "emoji": "🏜️",
    "lat": 31.9516,
    "lng": 35.924
  },
  {
    "he": "קהיר",
    "en": "Cairo",
    "country": "מצרים",
    "countryEn": "Egypt",
    "emoji": "🐫",
    "lat": 30.0444,
    "lng": 31.2357
  },
  {
    "he": "מרקש",
    "en": "Marrakesh",
    "country": "מרוקו",
    "countryEn": "Morocco",
    "emoji": "🕌",
    "lat": 31.6258,
    "lng": -7.9892
  },
  {
    "he": "קזבלנקה",
    "en": "Casablanca",
    "country": "מרוקו",
    "countryEn": "Morocco",
    "emoji": "🌊",
    "lat": 33.5945,
    "lng": -7.62
  },
  {
    "he": "בנגקוק",
    "en": "Bangkok",
    "country": "תאילנד",
    "countryEn": "Thailand",
    "emoji": "🛕",
    "lat": 13.7525,
    "lng": 100.4935
  },
  {
    "he": "פוקט",
    "en": "Phuket",
    "country": "תאילנד",
    "countryEn": "Thailand",
    "emoji": "🏝️",
    "lat": 7.9366,
    "lng": 98.3529
  },
  {
    "he": "צ׳יאנג מאי",
    "en": "Chiang Mai",
    "country": "תאילנד",
    "countryEn": "Thailand",
    "emoji": "🐘",
    "lat": 18.7883,
    "lng": 98.9859
  },
  {
    "he": "טוקיו",
    "en": "Tokyo",
    "country": "יפן",
    "countryEn": "Japan",
    "emoji": "🗾",
    "lat": 35.6769,
    "lng": 139.7639
  },
  {
    "he": "קיוטו",
    "en": "Kyoto",
    "country": "יפן",
    "countryEn": "Japan",
    "emoji": "⛩️",
    "lat": 35.0116,
    "lng": 135.7681
  },
  {
    "he": "אוסקה",
    "en": "Osaka",
    "country": "יפן",
    "countryEn": "Japan",
    "emoji": "🍜",
    "lat": 34.6938,
    "lng": 135.5015
  },
  {
    "he": "סיאול",
    "en": "Seoul",
    "country": "קוריאה",
    "countryEn": "South Korea",
    "emoji": "🏯",
    "lat": 37.5667,
    "lng": 126.9783
  },
  {
    "he": "בייג׳ינג",
    "en": "Beijing",
    "country": "סין",
    "countryEn": "China",
    "emoji": "🏯",
    "lat": 39.9057,
    "lng": 116.3913
  },
  {
    "he": "שנגחאי",
    "en": "Shanghai",
    "country": "סין",
    "countryEn": "China",
    "emoji": "🌆",
    "lat": 31.2313,
    "lng": 121.47
  },
  {
    "he": "הונג קונג",
    "en": "Hong Kong",
    "country": "הונג קונג",
    "countryEn": "Hong Kong",
    "emoji": "🏙️",
    "lat": 22.3492,
    "lng": 114.1858
  },
  {
    "he": "סינגפור",
    "en": "Singapore",
    "country": "סינגפור",
    "countryEn": "Singapore",
    "emoji": "🦁",
    "lat": 1.3571,
    "lng": 103.8195
  },
  {
    "he": "קואלה לומפור",
    "en": "Kuala Lumpur",
    "country": "מלזיה",
    "countryEn": "Malaysia",
    "emoji": "🏙️",
    "lat": 3.1517,
    "lng": 101.6942
  },
  {
    "he": "באלי",
    "en": "Denpasar",
    "country": "אינדונזיה",
    "countryEn": "Indonesia",
    "emoji": "🌺",
    "lat": -8.6653,
    "lng": 115.2176
  },
  {
    "he": "הו צ׳י מין",
    "en": "Ho Chi Minh City",
    "country": "וייטנאם",
    "countryEn": "Vietnam",
    "emoji": "🛵",
    "lat": 10.7737,
    "lng": 106.7166
  },
  {
    "he": "האנוי",
    "en": "Hanoi",
    "country": "וייטנאם",
    "countryEn": "Vietnam",
    "emoji": "🍲",
    "lat": 21.0283,
    "lng": 105.854
  },
  {
    "he": "דלהי",
    "en": "New Delhi",
    "country": "הודו",
    "countryEn": "India",
    "emoji": "🕌",
    "lat": 28.6139,
    "lng": 77.209
  },
  {
    "he": "מומבאי",
    "en": "Mumbai",
    "country": "הודו",
    "countryEn": "India",
    "emoji": "🎬",
    "lat": 19.055,
    "lng": 72.8692
  },
  {
    "he": "גואה",
    "en": "Panaji",
    "country": "הודו",
    "countryEn": "India",
    "emoji": "🏖️",
    "lat": 15.499,
    "lng": 73.8282
  },
  {
    "he": "קטמנדו",
    "en": "Kathmandu",
    "country": "נפאל",
    "countryEn": "Nepal",
    "emoji": "🏔️",
    "lat": 27.7083,
    "lng": 85.3206
  },
  {
    "he": "קולומבו",
    "en": "Colombo",
    "country": "סרי לנקה",
    "countryEn": "Sri Lanka",
    "emoji": "🌴",
    "lat": 6.9389,
    "lng": 79.8542
  },
  {
    "he": "מלדיביים",
    "en": "Male",
    "country": "מלדיביים",
    "countryEn": "Maldives",
    "emoji": "🏝️",
    "lat": 4.178,
    "lng": 73.5107
  },
  {
    "he": "ניו יורק",
    "en": "New York",
    "country": "ארצות הברית",
    "countryEn": "United States",
    "emoji": "🗽",
    "lat": 40.7127,
    "lng": -74.006
  },
  {
    "he": "לוס אנג׳לס",
    "en": "Los Angeles",
    "country": "ארצות הברית",
    "countryEn": "United States",
    "emoji": "🌴",
    "lat": 34.0537,
    "lng": -118.2428
  },
  {
    "he": "סן פרנסיסקו",
    "en": "San Francisco",
    "country": "ארצות הברית",
    "countryEn": "United States",
    "emoji": "🌉",
    "lat": 37.7879,
    "lng": -122.4075
  },
  {
    "he": "לאס וגאס",
    "en": "Las Vegas",
    "country": "ארצות הברית",
    "countryEn": "United States",
    "emoji": "🎰",
    "lat": 36.1674,
    "lng": -115.1484
  },
  {
    "he": "מיאמי",
    "en": "Miami",
    "country": "ארצות הברית",
    "countryEn": "United States",
    "emoji": "🏖️",
    "lat": 25.7742,
    "lng": -80.1936
  },
  {
    "he": "שיקגו",
    "en": "Chicago",
    "country": "ארצות הברית",
    "countryEn": "United States",
    "emoji": "🌃",
    "lat": 41.8756,
    "lng": -87.6244
  },
  {
    "he": "בוסטון",
    "en": "Boston",
    "country": "ארצות הברית",
    "countryEn": "United States",
    "emoji": "🎓",
    "lat": 42.3588,
    "lng": -71.0578
  },
  {
    "he": "וושינגטון",
    "en": "Washington",
    "country": "ארצות הברית",
    "countryEn": "United States",
    "emoji": "🏛️",
    "lat": 38.8951,
    "lng": -77.0364
  },
  {
    "he": "אורלנדו",
    "en": "Orlando",
    "country": "ארצות הברית",
    "countryEn": "United States",
    "emoji": "🎢",
    "lat": 28.5421,
    "lng": -81.379
  },
  {
    "he": "טורונטו",
    "en": "Toronto",
    "country": "קנדה",
    "countryEn": "Canada",
    "emoji": "🍁",
    "lat": 43.6535,
    "lng": -79.3839
  },
  {
    "he": "מונטריאול",
    "en": "Montreal",
    "country": "קנדה",
    "countryEn": "Canada",
    "emoji": "🍁",
    "lat": 45.5032,
    "lng": -73.5698
  },
  {
    "he": "ונקובר",
    "en": "Vancouver",
    "country": "קנדה",
    "countryEn": "Canada",
    "emoji": "🏔️",
    "lat": 49.2609,
    "lng": -123.114
  },
  {
    "he": "מקסיקו סיטי",
    "en": "Mexico City",
    "country": "מקסיקו",
    "countryEn": "Mexico",
    "emoji": "🌮",
    "lat": 19.3208,
    "lng": -99.1515
  },
  {
    "he": "קנקון",
    "en": "Cancun",
    "country": "מקסיקו",
    "countryEn": "Mexico",
    "emoji": "🏝️",
    "lat": 21.1527,
    "lng": -86.8426
  },
  {
    "he": "הוואנה",
    "en": "Havana",
    "country": "קובה",
    "countryEn": "Cuba",
    "emoji": "🚗",
    "lat": 23.1353,
    "lng": -82.359
  },
  {
    "he": "ריו דה ז׳ניירו",
    "en": "Rio de Janeiro",
    "country": "ברזיל",
    "countryEn": "Brazil",
    "emoji": "🌴",
    "lat": -22.911,
    "lng": -43.2094
  },
  {
    "he": "סאו פאולו",
    "en": "Sao Paulo",
    "country": "ברזיל",
    "countryEn": "Brazil",
    "emoji": "🏙️",
    "lat": -23.5507,
    "lng": -46.6334
  },
  {
    "he": "בואנוס איירס",
    "en": "Buenos Aires",
    "country": "ארגנטינה",
    "countryEn": "Argentina",
    "emoji": "💃",
    "lat": -34.6096,
    "lng": -58.3888
  },
  {
    "he": "סנטיאגו",
    "en": "Santiago",
    "country": "צ׳ילה",
    "countryEn": "Chile",
    "emoji": "🏔️",
    "lat": -33.4377,
    "lng": -70.6511
  },
  {
    "he": "לימה",
    "en": "Lima",
    "country": "פרו",
    "countryEn": "Peru",
    "emoji": "🦙",
    "lat": -12.046,
    "lng": -77.0306
  },
  {
    "he": "קוסקו",
    "en": "Cusco",
    "country": "פרו",
    "countryEn": "Peru",
    "emoji": "🏔️",
    "lat": -13.5171,
    "lng": -71.9785
  },
  {
    "he": "בוגוטה",
    "en": "Bogota",
    "country": "קולומביה",
    "countryEn": "Colombia",
    "emoji": "☕",
    "lat": 4.6534,
    "lng": -74.0836
  },
  {
    "he": "קייפטאון",
    "en": "Cape Town",
    "country": "דרום אפריקה",
    "countryEn": "South Africa",
    "emoji": "🐧",
    "lat": -33.9288,
    "lng": 18.4172
  },
  {
    "he": "ניירובי",
    "en": "Nairobi",
    "country": "קניה",
    "countryEn": "Kenya",
    "emoji": "🦁",
    "lat": -1.289,
    "lng": 36.8173
  },
  {
    "he": "סידני",
    "en": "Sydney",
    "country": "אוסטרליה",
    "countryEn": "Australia",
    "emoji": "🦘",
    "lat": -33.8698,
    "lng": 151.2083
  },
  {
    "he": "מלבורן",
    "en": "Melbourne",
    "country": "אוסטרליה",
    "countryEn": "Australia",
    "emoji": "☕",
    "lat": -37.8142,
    "lng": 144.9632
  },
  {
    "he": "אוקלנד",
    "en": "Auckland",
    "country": "ניו זילנד",
    "countryEn": "New Zealand",
    "emoji": "🥝",
    "lat": -36.8521,
    "lng": 174.7632
  },
  {
    "he": "תל אביב",
    "en": "Tel Aviv",
    "country": "ישראל",
    "countryEn": "Israel",
    "emoji": "🇮🇱",
    "lat": 32.0853,
    "lng": 34.7818
  },
  {
    "he": "ירושלים",
    "en": "Jerusalem",
    "country": "ישראל",
    "countryEn": "Israel",
    "emoji": "🕍",
    "lat": 31.7788,
    "lng": 35.2258
  },
  {
    "he": "אילת",
    "en": "Eilat",
    "country": "ישראל",
    "countryEn": "Israel",
    "emoji": "🐠",
    "lat": 29.5569,
    "lng": 34.9498
  }
]

/** Prefix-first, then substring, over both Hebrew and English names. */
export function searchCities(query, limit = 6) {
  const q = query.trim().toLowerCase()
  if (q.length < 1) return []

  const starts = []
  const contains = []

  for (const c of CITIES) {
    const he = c.he.toLowerCase()
    const en = c.en.toLowerCase()
    if (he.startsWith(q) || en.startsWith(q)) starts.push(c)
    else if (he.includes(q) || en.includes(q) || c.country.toLowerCase().includes(q) || c.countryEn.toLowerCase().includes(q)) contains.push(c)
    if (starts.length >= limit) break
  }

  return [...starts, ...contains].slice(0, limit)
}
